caseSensitive: true
dictionaries:
  - EN_US
  - css
  - companies
  - html
  - fonts
  - filetypes
  - node
  - npm
  - typescript
words:
  - Amador
  - APCA
  - Campistron
  - Coyier
  - D’Arcy
  - Dalbin
  - Dalton Maag
  - Digg
  - downvote
  - Döhren
  - Drasner
  - Dribbble
  - Durko
  - Fontsmith
  - Fontstand
  - FOUC
  - Fuzzco
  - Gimbel
  - Giphy
  - Grilli
  - Gwenyth
  - Hayao
  - hermeticity
  - HTMLWG
  - hoverable
  - IMDB
  - janky
  - Kemar
  - Klim
  - Kyra
  - laggy
  - Larkin
  - Lightspeed
  - MCKL
  - mailgun
  - mentee
  - Miyazaki
  - Muscarella
  - Nubank
  - OKLAB
  - OKLCH
  - Optimo
  - overengineered
  - Qwik
  - Paltrow
  - Playtype
  - Pngcrush
  - PNGOUT
  - Preethi
  - Schott
  - Sharptype
  - Skypack
  - SMACSS
  - Starlark
  - Steinberg
  - Stratigakis
  - Ström
  - Sudtipos
  - Teleportal
  - Thanasi
  - Tibaldi
  - tierlist
  - Turbopack
  - Turborepo
  - Typofonderie
  - underengineered
  - unga bunga
  - Urkel
  - upvote
  - Vaynerchuk
  - Wayans
  - WCAG
  - WYSIWYG
  - wysiwyg
  - Zeit
  - Zopfli
